/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-14 at 01:48:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruiqi_test.frontend.model;

/**
 * Model definition for FrontendRpcAmendOrderRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the frontend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FrontendRpcAmendOrderRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("change_id") @com.google.api.client.json.JsonString
  private java.lang.Long changeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("order_id")
  private java.lang.String orderId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("product_amounts")
  private java.util.List<java.lang.Double> productAmounts;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("product_ids")
  private java.util.List<java.lang.String> productIds;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("target_date")
  private com.google.api.client.util.DateTime targetDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String token;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getChangeId() {
    return changeId;
  }

  /**
   * @param changeId changeId or {@code null} for none
   */
  public FrontendRpcAmendOrderRequest setChangeId(java.lang.Long changeId) {
    this.changeId = changeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public FrontendRpcAmendOrderRequest setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOrderId() {
    return orderId;
  }

  /**
   * @param orderId orderId or {@code null} for none
   */
  public FrontendRpcAmendOrderRequest setOrderId(java.lang.String orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Double> getProductAmounts() {
    return productAmounts;
  }

  /**
   * @param productAmounts productAmounts or {@code null} for none
   */
  public FrontendRpcAmendOrderRequest setProductAmounts(java.util.List<java.lang.Double> productAmounts) {
    this.productAmounts = productAmounts;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getProductIds() {
    return productIds;
  }

  /**
   * @param productIds productIds or {@code null} for none
   */
  public FrontendRpcAmendOrderRequest setProductIds(java.util.List<java.lang.String> productIds) {
    this.productIds = productIds;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getTargetDate() {
    return targetDate;
  }

  /**
   * @param targetDate targetDate or {@code null} for none
   */
  public FrontendRpcAmendOrderRequest setTargetDate(com.google.api.client.util.DateTime targetDate) {
    this.targetDate = targetDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getToken() {
    return token;
  }

  /**
   * @param token token or {@code null} for none
   */
  public FrontendRpcAmendOrderRequest setToken(java.lang.String token) {
    this.token = token;
    return this;
  }

  @Override
  public FrontendRpcAmendOrderRequest set(String fieldName, Object value) {
    return (FrontendRpcAmendOrderRequest) super.set(fieldName, value);
  }

  @Override
  public FrontendRpcAmendOrderRequest clone() {
    return (FrontendRpcAmendOrderRequest) super.clone();
  }

}
