/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-14 at 01:48:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruiqi_test.frontend.model;

/**
 * Model definition for FrontendRpcSmsOrderItem.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the frontend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FrontendRpcSmsOrderItem extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double amount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("descimal_unit")
  private java.lang.Boolean descimalUnit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("image_url")
  private java.lang.String imageUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("name_cn")
  private java.lang.String nameCn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("name_en")
  private java.lang.String nameEn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("product_id")
  private java.lang.String productId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("unit_name")
  private java.lang.String unitName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getAmount() {
    return amount;
  }

  /**
   * @param amount amount or {@code null} for none
   */
  public FrontendRpcSmsOrderItem setAmount(java.lang.Double amount) {
    this.amount = amount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDescimalUnit() {
    return descimalUnit;
  }

  /**
   * @param descimalUnit descimalUnit or {@code null} for none
   */
  public FrontendRpcSmsOrderItem setDescimalUnit(java.lang.Boolean descimalUnit) {
    this.descimalUnit = descimalUnit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImageUrl() {
    return imageUrl;
  }

  /**
   * @param imageUrl imageUrl or {@code null} for none
   */
  public FrontendRpcSmsOrderItem setImageUrl(java.lang.String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameCn() {
    return nameCn;
  }

  /**
   * @param nameCn nameCn or {@code null} for none
   */
  public FrontendRpcSmsOrderItem setNameCn(java.lang.String nameCn) {
    this.nameCn = nameCn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameEn() {
    return nameEn;
  }

  /**
   * @param nameEn nameEn or {@code null} for none
   */
  public FrontendRpcSmsOrderItem setNameEn(java.lang.String nameEn) {
    this.nameEn = nameEn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProductId() {
    return productId;
  }

  /**
   * @param productId productId or {@code null} for none
   */
  public FrontendRpcSmsOrderItem setProductId(java.lang.String productId) {
    this.productId = productId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUnitName() {
    return unitName;
  }

  /**
   * @param unitName unitName or {@code null} for none
   */
  public FrontendRpcSmsOrderItem setUnitName(java.lang.String unitName) {
    this.unitName = unitName;
    return this;
  }

  @Override
  public FrontendRpcSmsOrderItem set(String fieldName, Object value) {
    return (FrontendRpcSmsOrderItem) super.set(fieldName, value);
  }

  @Override
  public FrontendRpcSmsOrderItem clone() {
    return (FrontendRpcSmsOrderItem) super.clone();
  }

}
