/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-14 at 01:48:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruiqi_test.frontend.model;

/**
 * Model definition for FrontendRpcProductCollectionResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the frontend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FrontendRpcProductCollectionResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long code;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<FrontendRpcSmsProduct> items;

  static {
    // hack to force ProGuard to consider FrontendRpcSmsProduct used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(FrontendRpcSmsProduct.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("message_cn")
  private java.lang.String messageCn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("message_en")
  private java.lang.String messageEn;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCode() {
    return code;
  }

  /**
   * @param code code or {@code null} for none
   */
  public FrontendRpcProductCollectionResponse setCode(java.lang.Long code) {
    this.code = code;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<FrontendRpcSmsProduct> getItems() {
    return items;
  }

  /**
   * @param items items or {@code null} for none
   */
  public FrontendRpcProductCollectionResponse setItems(java.util.List<FrontendRpcSmsProduct> items) {
    this.items = items;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMessageCn() {
    return messageCn;
  }

  /**
   * @param messageCn messageCn or {@code null} for none
   */
  public FrontendRpcProductCollectionResponse setMessageCn(java.lang.String messageCn) {
    this.messageCn = messageCn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMessageEn() {
    return messageEn;
  }

  /**
   * @param messageEn messageEn or {@code null} for none
   */
  public FrontendRpcProductCollectionResponse setMessageEn(java.lang.String messageEn) {
    this.messageEn = messageEn;
    return this;
  }

  @Override
  public FrontendRpcProductCollectionResponse set(String fieldName, Object value) {
    return (FrontendRpcProductCollectionResponse) super.set(fieldName, value);
  }

  @Override
  public FrontendRpcProductCollectionResponse clone() {
    return (FrontendRpcProductCollectionResponse) super.clone();
  }

}
