/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-14 at 01:48:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruiqi_test.frontend.model;

/**
 * Model definition for FrontendRpcSmsProduct.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the frontend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FrontendRpcSmsProduct extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("change_id") @com.google.api.client.json.JsonString
  private java.lang.Long changeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean deleted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("descimal_unit")
  private java.lang.Boolean descimalUnit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("image_url")
  private java.lang.String imageUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("name_cn")
  private java.lang.String nameCn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("name_en")
  private java.lang.String nameEn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("unit_name")
  private java.lang.String unitName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getChangeId() {
    return changeId;
  }

  /**
   * @param changeId changeId or {@code null} for none
   */
  public FrontendRpcSmsProduct setChangeId(java.lang.Long changeId) {
    this.changeId = changeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDeleted() {
    return deleted;
  }

  /**
   * @param deleted deleted or {@code null} for none
   */
  public FrontendRpcSmsProduct setDeleted(java.lang.Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDescimalUnit() {
    return descimalUnit;
  }

  /**
   * @param descimalUnit descimalUnit or {@code null} for none
   */
  public FrontendRpcSmsProduct setDescimalUnit(java.lang.Boolean descimalUnit) {
    this.descimalUnit = descimalUnit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public FrontendRpcSmsProduct setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImageUrl() {
    return imageUrl;
  }

  /**
   * @param imageUrl imageUrl or {@code null} for none
   */
  public FrontendRpcSmsProduct setImageUrl(java.lang.String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameCn() {
    return nameCn;
  }

  /**
   * @param nameCn nameCn or {@code null} for none
   */
  public FrontendRpcSmsProduct setNameCn(java.lang.String nameCn) {
    this.nameCn = nameCn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameEn() {
    return nameEn;
  }

  /**
   * @param nameEn nameEn or {@code null} for none
   */
  public FrontendRpcSmsProduct setNameEn(java.lang.String nameEn) {
    this.nameEn = nameEn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public FrontendRpcSmsProduct setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUnitName() {
    return unitName;
  }

  /**
   * @param unitName unitName or {@code null} for none
   */
  public FrontendRpcSmsProduct setUnitName(java.lang.String unitName) {
    this.unitName = unitName;
    return this;
  }

  @Override
  public FrontendRpcSmsProduct set(String fieldName, Object value) {
    return (FrontendRpcSmsProduct) super.set(fieldName, value);
  }

  @Override
  public FrontendRpcSmsProduct clone() {
    return (FrontendRpcSmsProduct) super.clone();
  }

}
