/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-14 at 01:48:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruiqi_test.frontend.model;

/**
 * Model definition for FrontendRpcSmsUser.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the frontend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FrontendRpcSmsUser extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_cancel_order")
  private java.lang.Boolean canCancelOrder;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_change_storage")
  private java.lang.Boolean canChangeStorage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_confirm_order")
  private java.lang.Boolean canConfirmOrder;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_create_order")
  private java.lang.Boolean canCreateOrder;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_deliver_order")
  private java.lang.Boolean canDeliverOrder;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_edit_order")
  private java.lang.Boolean canEditOrder;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_edit_template")
  private java.lang.Boolean canEditTemplate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_receive_order")
  private java.lang.Boolean canReceiveOrder;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_view_history")
  private java.lang.Boolean canViewHistory;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("can_view_statistic")
  private java.lang.Boolean canViewStatistic;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("company_name_cn")
  private java.lang.String companyNameCn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("company_name_en")
  private java.lang.String companyNameEn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("display_name")
  private java.lang.String displayName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("is_manager")
  private java.lang.Boolean isManager;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("login_name")
  private java.lang.String loginName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("parent_id")
  private java.lang.String parentId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String role;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanCancelOrder() {
    return canCancelOrder;
  }

  /**
   * @param canCancelOrder canCancelOrder or {@code null} for none
   */
  public FrontendRpcSmsUser setCanCancelOrder(java.lang.Boolean canCancelOrder) {
    this.canCancelOrder = canCancelOrder;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanChangeStorage() {
    return canChangeStorage;
  }

  /**
   * @param canChangeStorage canChangeStorage or {@code null} for none
   */
  public FrontendRpcSmsUser setCanChangeStorage(java.lang.Boolean canChangeStorage) {
    this.canChangeStorage = canChangeStorage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanConfirmOrder() {
    return canConfirmOrder;
  }

  /**
   * @param canConfirmOrder canConfirmOrder or {@code null} for none
   */
  public FrontendRpcSmsUser setCanConfirmOrder(java.lang.Boolean canConfirmOrder) {
    this.canConfirmOrder = canConfirmOrder;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanCreateOrder() {
    return canCreateOrder;
  }

  /**
   * @param canCreateOrder canCreateOrder or {@code null} for none
   */
  public FrontendRpcSmsUser setCanCreateOrder(java.lang.Boolean canCreateOrder) {
    this.canCreateOrder = canCreateOrder;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanDeliverOrder() {
    return canDeliverOrder;
  }

  /**
   * @param canDeliverOrder canDeliverOrder or {@code null} for none
   */
  public FrontendRpcSmsUser setCanDeliverOrder(java.lang.Boolean canDeliverOrder) {
    this.canDeliverOrder = canDeliverOrder;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanEditOrder() {
    return canEditOrder;
  }

  /**
   * @param canEditOrder canEditOrder or {@code null} for none
   */
  public FrontendRpcSmsUser setCanEditOrder(java.lang.Boolean canEditOrder) {
    this.canEditOrder = canEditOrder;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanEditTemplate() {
    return canEditTemplate;
  }

  /**
   * @param canEditTemplate canEditTemplate or {@code null} for none
   */
  public FrontendRpcSmsUser setCanEditTemplate(java.lang.Boolean canEditTemplate) {
    this.canEditTemplate = canEditTemplate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanReceiveOrder() {
    return canReceiveOrder;
  }

  /**
   * @param canReceiveOrder canReceiveOrder or {@code null} for none
   */
  public FrontendRpcSmsUser setCanReceiveOrder(java.lang.Boolean canReceiveOrder) {
    this.canReceiveOrder = canReceiveOrder;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanViewHistory() {
    return canViewHistory;
  }

  /**
   * @param canViewHistory canViewHistory or {@code null} for none
   */
  public FrontendRpcSmsUser setCanViewHistory(java.lang.Boolean canViewHistory) {
    this.canViewHistory = canViewHistory;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanViewStatistic() {
    return canViewStatistic;
  }

  /**
   * @param canViewStatistic canViewStatistic or {@code null} for none
   */
  public FrontendRpcSmsUser setCanViewStatistic(java.lang.Boolean canViewStatistic) {
    this.canViewStatistic = canViewStatistic;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCompanyNameCn() {
    return companyNameCn;
  }

  /**
   * @param companyNameCn companyNameCn or {@code null} for none
   */
  public FrontendRpcSmsUser setCompanyNameCn(java.lang.String companyNameCn) {
    this.companyNameCn = companyNameCn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCompanyNameEn() {
    return companyNameEn;
  }

  /**
   * @param companyNameEn companyNameEn or {@code null} for none
   */
  public FrontendRpcSmsUser setCompanyNameEn(java.lang.String companyNameEn) {
    this.companyNameEn = companyNameEn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayName() {
    return displayName;
  }

  /**
   * @param displayName displayName or {@code null} for none
   */
  public FrontendRpcSmsUser setDisplayName(java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public FrontendRpcSmsUser setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsManager() {
    return isManager;
  }

  /**
   * @param isManager isManager or {@code null} for none
   */
  public FrontendRpcSmsUser setIsManager(java.lang.Boolean isManager) {
    this.isManager = isManager;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLoginName() {
    return loginName;
  }

  /**
   * @param loginName loginName or {@code null} for none
   */
  public FrontendRpcSmsUser setLoginName(java.lang.String loginName) {
    this.loginName = loginName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getParentId() {
    return parentId;
  }

  /**
   * @param parentId parentId or {@code null} for none
   */
  public FrontendRpcSmsUser setParentId(java.lang.String parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public FrontendRpcSmsUser setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRole() {
    return role;
  }

  /**
   * @param role role or {@code null} for none
   */
  public FrontendRpcSmsUser setRole(java.lang.String role) {
    this.role = role;
    return this;
  }

  @Override
  public FrontendRpcSmsUser set(String fieldName, Object value) {
    return (FrontendRpcSmsUser) super.set(fieldName, value);
  }

  @Override
  public FrontendRpcSmsUser clone() {
    return (FrontendRpcSmsUser) super.clone();
  }

}
