/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-14 at 01:48:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruiqi_test.frontend.model;

/**
 * Model definition for FrontendRpcSmsOperate.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the frontend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FrontendRpcSmsOperate extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String action;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("operate_items")
  private java.util.List<FrontendRpcSmsOperateItem> operateItems;

  static {
    // hack to force ProGuard to consider FrontendRpcSmsOperateItem used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(FrontendRpcSmsOperateItem.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("operate_time")
  private FrontendRpcSmsTimeOperate operateTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operator;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAction() {
    return action;
  }

  /**
   * @param action action or {@code null} for none
   */
  public FrontendRpcSmsOperate setAction(java.lang.String action) {
    this.action = action;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public FrontendRpcSmsOperate setDate(java.lang.Long date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public FrontendRpcSmsOperate setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<FrontendRpcSmsOperateItem> getOperateItems() {
    return operateItems;
  }

  /**
   * @param operateItems operateItems or {@code null} for none
   */
  public FrontendRpcSmsOperate setOperateItems(java.util.List<FrontendRpcSmsOperateItem> operateItems) {
    this.operateItems = operateItems;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public FrontendRpcSmsTimeOperate getOperateTime() {
    return operateTime;
  }

  /**
   * @param operateTime operateTime or {@code null} for none
   */
  public FrontendRpcSmsOperate setOperateTime(FrontendRpcSmsTimeOperate operateTime) {
    this.operateTime = operateTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOperator() {
    return operator;
  }

  /**
   * @param operator operator or {@code null} for none
   */
  public FrontendRpcSmsOperate setOperator(java.lang.String operator) {
    this.operator = operator;
    return this;
  }

  @Override
  public FrontendRpcSmsOperate set(String fieldName, Object value) {
    return (FrontendRpcSmsOperate) super.set(fieldName, value);
  }

  @Override
  public FrontendRpcSmsOperate clone() {
    return (FrontendRpcSmsOperate) super.clone();
  }

}
