/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-14 at 01:48:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruiqi_test.frontend.model;

/**
 * Model definition for FrontendRpcReportRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the frontend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FrontendRpcReportRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("customer_ids")
  private java.util.List<java.lang.String> customerIds;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<com.google.api.client.util.DateTime> dates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String token;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCustomerIds() {
    return customerIds;
  }

  /**
   * @param customerIds customerIds or {@code null} for none
   */
  public FrontendRpcReportRequest setCustomerIds(java.util.List<java.lang.String> customerIds) {
    this.customerIds = customerIds;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<com.google.api.client.util.DateTime> getDates() {
    return dates;
  }

  /**
   * @param dates dates or {@code null} for none
   */
  public FrontendRpcReportRequest setDates(java.util.List<com.google.api.client.util.DateTime> dates) {
    this.dates = dates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getToken() {
    return token;
  }

  /**
   * @param token token or {@code null} for none
   */
  public FrontendRpcReportRequest setToken(java.lang.String token) {
    this.token = token;
    return this;
  }

  @Override
  public FrontendRpcReportRequest set(String fieldName, Object value) {
    return (FrontendRpcReportRequest) super.set(fieldName, value);
  }

  @Override
  public FrontendRpcReportRequest clone() {
    return (FrontendRpcReportRequest) super.clone();
  }

}
