/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-14 at 01:48:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.ruiqi_test.frontend.model;

/**
 * Model definition for FrontendRpcSmsCustomer.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the frontend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FrontendRpcSmsCustomer extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("change_id") @com.google.api.client.json.JsonString
  private java.lang.Long changeId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("group_id")
  private java.lang.String groupId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("group_name_cn")
  private java.lang.String groupNameCn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("group_name_en")
  private java.lang.String groupNameEn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("name_cn")
  private java.lang.String nameCn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("name_en")
  private java.lang.String nameEn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<FrontendRpcSmsOrderTemplate> templates;

  static {
    // hack to force ProGuard to consider FrontendRpcSmsOrderTemplate used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(FrontendRpcSmsOrderTemplate.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getChangeId() {
    return changeId;
  }

  /**
   * @param changeId changeId or {@code null} for none
   */
  public FrontendRpcSmsCustomer setChangeId(java.lang.Long changeId) {
    this.changeId = changeId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroupId() {
    return groupId;
  }

  /**
   * @param groupId groupId or {@code null} for none
   */
  public FrontendRpcSmsCustomer setGroupId(java.lang.String groupId) {
    this.groupId = groupId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroupNameCn() {
    return groupNameCn;
  }

  /**
   * @param groupNameCn groupNameCn or {@code null} for none
   */
  public FrontendRpcSmsCustomer setGroupNameCn(java.lang.String groupNameCn) {
    this.groupNameCn = groupNameCn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroupNameEn() {
    return groupNameEn;
  }

  /**
   * @param groupNameEn groupNameEn or {@code null} for none
   */
  public FrontendRpcSmsCustomer setGroupNameEn(java.lang.String groupNameEn) {
    this.groupNameEn = groupNameEn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public FrontendRpcSmsCustomer setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameCn() {
    return nameCn;
  }

  /**
   * @param nameCn nameCn or {@code null} for none
   */
  public FrontendRpcSmsCustomer setNameCn(java.lang.String nameCn) {
    this.nameCn = nameCn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameEn() {
    return nameEn;
  }

  /**
   * @param nameEn nameEn or {@code null} for none
   */
  public FrontendRpcSmsCustomer setNameEn(java.lang.String nameEn) {
    this.nameEn = nameEn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<FrontendRpcSmsOrderTemplate> getTemplates() {
    return templates;
  }

  /**
   * @param templates templates or {@code null} for none
   */
  public FrontendRpcSmsCustomer setTemplates(java.util.List<FrontendRpcSmsOrderTemplate> templates) {
    this.templates = templates;
    return this;
  }

  @Override
  public FrontendRpcSmsCustomer set(String fieldName, Object value) {
    return (FrontendRpcSmsCustomer) super.set(fieldName, value);
  }

  @Override
  public FrontendRpcSmsCustomer clone() {
    return (FrontendRpcSmsCustomer) super.clone();
  }

}
